/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import lab_2.Course;
import lab_2.Lecturer;
import lab_2.Subject;

/**
 *
 * @author ASUS
 */
public class Lecturer_Signup extends javax.swing.JFrame {

    private int Lid;
    private String Lname;
    private int LAge;
    private String LUsername;
    private String LCPassword;
    private ArrayList<Course> sublist=new ArrayList<>();
    private LecControl LecControl=new LecControl();
    public static Lecturer_Signup lecSignUp=new Lecturer_Signup();
    private Lecturer lec=new Lecturer();
    /**
     * Creates new form Lecturer_Signup
     */
    public Lecturer_Signup() {
        initComponents();
    }
    
    Connection con;
    PreparedStatement prst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        txtLage = new javax.swing.JTextField();
        txtLUsername = new javax.swing.JTextField();
        txtLpassword = new javax.swing.JPasswordField();
        txtCLpassword = new javax.swing.JPasswordField();
        btnSignup = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        checkC3 = new javax.swing.JCheckBox();
        checkC2 = new javax.swing.JCheckBox();
        checkC1 = new javax.swing.JCheckBox();
        txtLid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("University Management System");
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Lecturer Registration Form");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(52, 13, 426, 42);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name                       : ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(48, 140, 219, 28);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Age                           : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 200, 216, 28);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("UserName               : ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(44, 246, 211, 28);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password                : ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(44, 302, 208, 28);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Confirm Password : ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(44, 351, 210, 28);
        getContentPane().add(txtLname);
        txtLname.setBounds(285, 143, 450, 28);
        getContentPane().add(txtLage);
        txtLage.setBounds(290, 200, 440, 28);
        getContentPane().add(txtLUsername);
        txtLUsername.setBounds(288, 249, 440, 28);

        txtLpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtLpassword);
        txtLpassword.setBounds(290, 300, 440, 28);
        getContentPane().add(txtCLpassword);
        txtCLpassword.setBounds(290, 350, 440, 28);

        btnSignup.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnSignup.setText("Sign up");
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignup);
        btnSignup.setBounds(240, 610, 147, 51);

        btnCancel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel);
        btnCancel.setBounds(610, 610, 137, 51);

        checkC3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        checkC3.setForeground(new java.awt.Color(255, 255, 255));
        checkC3.setText("SENG1113_Data_Structures_and_Algorithms");
        getContentPane().add(checkC3);
        checkC3.setBounds(177, 548, 499, 37);

        checkC2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        checkC2.setForeground(new java.awt.Color(255, 255, 255));
        checkC2.setText("SENG1112_Fundamantales_of_Engineering");
        getContentPane().add(checkC2);
        checkC2.setBounds(177, 480, 469, 37);

        checkC1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        checkC1.setForeground(new java.awt.Color(255, 255, 255));
        checkC1.setText("SENG1111_Introduction_to_Programming");
        getContentPane().add(checkC1);
        checkC1.setBounds(177, 416, 469, 37);
        getContentPane().add(txtLid);
        txtLid.setBounds(290, 90, 450, 28);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Lecturer Id             :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 90, 219, 28);

        jLabel8.setIcon(new javax.swing.ImageIcon("E:\\New folder\\wallpapers\\Aqua-01-2.3.001-bigpicture_01_11.jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 60, 720, 540);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(440, 610, 120, 51);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLpasswordActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        // TODO add your handling code here:
        if(txtLid.getText().length()==0){
              JOptionPane.showMessageDialog(this,"Please Enter Lecturer Id");
        }
        else if(txtLname.getText().length()==0){
              JOptionPane.showMessageDialog(this,"Please Enter Name");
        }
        else if(txtLage.getText().length()==0){
              JOptionPane.showMessageDialog(this,"Please Enter Age");
        }
        else if(txtLUsername.getText().length()==0){
              JOptionPane.showMessageDialog(this,"Please Enter Username");
        }
        else if(txtLpassword.getText().length()==0){
              JOptionPane.showMessageDialog(this,"Please Enter Password");
        }
        else if(txtLpassword.getText().equals(txtCLpassword.getText())==false){
            JOptionPane.showMessageDialog(this,"Password Not Matched");
        }
        else{
            try {
                
            JFrame frame=new JFrame();
            Lid=Integer.parseInt(txtLid.getText());
            LUsername=txtLUsername.getText();
            Lname=txtLname.getText();
            LAge=Integer.parseInt(txtLage.getText());
            LCPassword=txtCLpassword.getText();
            lec=LecControl.lecSignIn(LUsername, LCPassword);
            if(lec!=null){
                JOptionPane.showMessageDialog(frame, "UserName and Password Already Taken Try another user..");
            
            }else{
                if(checkC1.isSelected()){
                Course subject1=new Course(String.valueOf(Subject.SENG1111_Introduction_to_Programming),1);
                sublist.add(subject1);
            }
            if(checkC2.isSelected()){
                Course subject2=new Course(String.valueOf(Subject.SENG1112_Fundamantales_of_Engineering),2);
                sublist.add(subject2);
            }
            if(checkC3.isSelected()){
                Course subject3=new Course(String.valueOf(Subject.SENG1113_Data_Structures_and_Algorithms),3);
                sublist.add(subject3);
            }
            LecControl.lecSignUp(Lid, Lname, LAge, LUsername, LCPassword, sublist);
            }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Student_Signup.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Student_Signup.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btnSignupActionPerformed
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtLid.setText("");
        txtLUsername.setText("");
        txtLname.setText("");
        txtLage.setText("");
        txtLpassword.setText("");
        txtCLpassword.setText("");
        checkC1.setSelected(false);
        checkC2.setSelected(false);
        checkC3.setSelected(false);
    }//GEN-LAST:event_jButton1ActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lecturer_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lecturer_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lecturer_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lecturer_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lecturer_Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSignup;
    private javax.swing.JCheckBox checkC1;
    private javax.swing.JCheckBox checkC2;
    private javax.swing.JCheckBox checkC3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField txtCLpassword;
    private javax.swing.JTextField txtLUsername;
    private javax.swing.JTextField txtLage;
    private javax.swing.JTextField txtLid;
    private javax.swing.JTextField txtLname;
    private javax.swing.JPasswordField txtLpassword;
    // End of variables declaration//GEN-END:variables

    static class setVisible {

        public setVisible(boolean b) {
        }
    }
}
